DROP table member CASCADE CONSTRAINTS;

CREATE TABLE COMPRI.member
(
member_id NUMBER GENERATED BY DEFAULT AS IDENTITY
CONSTRAINT member_member_id_pk PRIMARY KEY, 

login_id VARCHAR2(20) NOT NULL,

alias VARCHAR2(10) NOT NULL,

money NUMBER NOT NULL,

email VARCHAR2(30) NULL,

mobile_num NUMBER NULL,

sns VARCHAR2(10) NULL,

pwd VARCHAR2(20) NOT NULL,

join_date TIMESTAMP NOT NULL,

point NUMBER NOT NULL,

authority_code VARCHAR2(10) NOT NULL,
CONSTRAINT member_authority_code_ck CHECK(authority_code in ('read', 'read+write')),

admin_account VARCHAR2(10) NOT NULL,
CONSTRAINT member_admin_account_ck CHECK (admin_account in ('user', 'admin'))
);

DROP table non_member CASCADE CONSTRAINTS;

CREATE TABLE COMPRI.non_member
(
non_member_id NUMBER GENERATED BY DEFAULT AS IDENTITY
CONSTRAINT non_member_non_member_id_pk PRIMARY KEY, 

non_member_ip VARCHAR2(30) NOT NULL,

authority_code VARCHAR2(10) NOT NULL,
CONSTRAINT non_member_authority_code_ck CHECK(authority_code in ('read', 'read+write'))
);

DROP table retail CASCADE CONSTRAINTS;

CREATE TABLE COMPRI.retail
(
retail_id NUMBER GENERATED BY DEFAULT AS IDENTITY
	CONSTRAINT retail_retail_id_pk PRIMARY KEY,

retail_name VARCHAR2(20)  NOT NULL,

retail_addr VARCHAR2(50)  NOT NULL
);

DROP table cart CASCADE CONSTRAINTS;

CREATE TABLE COMPRI.cart
(
cart_id NUMBER  GENERATED BY DEFAULT AS IDENTITY
	CONSTRAINT cart_cart_id_pk PRIMARY KEY,

cart_creation_date TIMESTAMP  NOT NULL,

API_date TIMESTAMP NOT NULL
);

DROP table member_retail_cart CASCADE CONSTRAINTS;

CREATE TABLE COMPRI.member_retail_cart
( 
member_retail_cart_num NUMBER GENERATED BY DEFAULT AS IDENTITY
CONSTRAINT member_retail_cart_member_retail_cart_num_pk PRIMARY KEY
);